---
- name: Existing install
  stat:
    path: "{{ ansible_user_dir }}/.cargo/bin/rustup"
  register: install

- name: Download installer
  get_url:
    dest: "{{ ansible_user_dir }}/rustup-init.sh"
    mode: 0755
    url: https://sh.rustup.rs
  when: not install.stat.exists

- name: Execute rustup-init.sh
  shell: "{{ ansible_user_dir }}/rustup-init.sh -y"
  when: not install.stat.exists

- name: Remove rustup-init.sh
  file:
    path: "{{ ansible_user_dir }}/rustup-init.sh"
    state: absent
