---
- name: Install
  homebrew:
    name: k9s
    state: latest

- name: Directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/k9s"
    state: directory

- name: skin.yml
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/Library/Application Support/k9s/skin.yml"
    src: "skin.yml"
