#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! [[ -x "$(command -v brew)" ]]; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo >> /Users/Aleksandr_Stasko/.zprofile
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/Aleksandr_Stasko/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
    #brew install --cask font-awesome-terminal-fonts
    #brew install --cask logi-options+
    #brew install --cask spotify

  fi

  if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  fi
fi
