#!/bin/bash

system_type=$(uname -s)

yadm remote set-url origin "git@github.com:AlexStasko/dotfiles-osx.git"

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! [[ -x "$(command -v brew)" ]]; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  echo "Updating homebrew bundle"
  brew bundle --global

  if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  fi
fi
