---
- name: Install
  homebrew:
    name:
      - jq
      - openssl
    state: latest

- name: Create bin dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: Tap fonts
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Install fonts
  homebrew_cask:
    name: 
      - font-meslo-lg-nerd-font
      - font-fontawesome
    state: latest
